### ISSUE TITLE
database-cleaner doesn't install on systems lacking Postgres

### ISSUE THREAD

**Issue by rwilcox** [emerleite/node-database-cleaner#20]
My project is a typical MEAN stack app: MongoDB as my database, no MySQL or Postgres in sight.

I've found I can no longer install the latest database cleaner: it fails at install time!

I create a fresh npm package to demo this problem. Here is my package.json from it

	{
	  "name": "test_proj",
	  "version": "1.0.0",
	  "description": "Testing database_cleaner",
	  "main": "index.js",
	  "scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
	  },
	  "dependencies": {
		"database-cleaner": "*"
	  },
	  "author": "",
	  "license": "ISC"
	}

As you see, this is pretty much the simplest Node project you can have, except for the dependency on database-cleaner

When I npm install this package I get:

	% npm install                                                                                                             
	npm WARN package.json test_proj@1.0.0 No repository field.
	npm WARN package.json test_proj@1.0.0 No README data

	> kerberos@0.0.4 install /home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/mongodb/node_modules/kerberos
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	make: Entering directory `/home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/mongodb/node_modules/kerberos/build'
	  SOLINK_MODULE(target) Release/obj.target/kerberos.node
	  SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
	  COPY Release/kerberos.node
	make: Leaving directory `/home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/mongodb/node_modules/kerberos/build'

	> bson@0.2.15 install /home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/mongodb/node_modules/bson
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	make: Entering directory `/home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/mongodb/node_modules/bson/build'
	  CXX(target) Release/obj.target/bson/ext/bson.o
	  SOLINK_MODULE(target) Release/obj.target/bson.node
	  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
	  COPY Release/bson.node
	make: Leaving directory `/home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/mongodb/node_modules/bson/build'

	> pg@3.4.2 install /home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/pg
	> node-gyp rebuild || (exit 0)

	/bin/sh: 1: pg_config: not found
	gyp: Call to 'pg_config --libdir' returned exit status 127. while trying to load binding.gyp
	gyp ERR! configure error
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
	gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
	gyp ERR! System Linux 3.11.0-15-generic
	gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/vagrant/Temp/test_proj/node_modules/database-cleaner/node_modules/pg
	gyp ERR! node -v v0.10.33
	gyp ERR! node-gyp -v v1.0.1
	gyp ERR! not ok

This makes sense to me: I don't have pg_config installed on my system, because I'm not using Postgres! But I should be able to use database-cleaner without it!

I'm sorry I only have time to file this issue, not track it down further. For now I've reverted to database-cleaner 0.8.0, but it would be nice to use the latest cleaner version ;)

**Comment by emerleite** [comment]
Issue #21 will solve this.

**Comment by emerleite** [comment]
Just released 0.9.1 with the fix.
