### ISSUE TITLE
Too many dependencies :(

### ISSUE THREAD

**Issue by sheerun** [emerleite/node-database-cleaner#21]
Could you move `dependencies` to `devDependencies`, so I can choose what databases to install?

Currently installing `database-cleaner` installs all adapters, which is a very heavy operation.

See for example knex: https://github.com/tgriesser/knex/blob/master/package.json

**Comment by emerleite** [comment]
You're right. I'll do it ;)

**Comment by sheerun** [comment]
:+1:

**Comment by emerleite** [comment]
Just released 0.9.1 with the fix.
