### ISSUE TITLE
Bug for postgres cleaner

### ISSUE THREAD

**Issue by Bayees** [emerleite/node-database-cleaner#28]
Line 63 should be 
    db.query('DELETE FROM "' + table['table_name'] + '"', function(err) {

to get the right table name

**Comment by emerleite** [comment]
I'll take a look.

**Comment by emerleite** [comment]
@Bayees for me it's working fine. Could you give more information to try to reproduce?

**Comment by chamini2** [comment]
This seems to be fixed by #23

**Comment by emerleite** [comment]
Thanks @chamini2. Can you confirm It's ok @Bayees?

**Comment by emerleite** [comment]
Fixed by #23
