### ISSUE TITLE
Config is not relative to executing dir

### ISSUE THREAD

**Issue by knappe** [emerleite/node-database-cleaner#31]
We should do this instead:

```
  try {
    config = require("../../../config/cleaner-config.js");
  } catch (e) {
    config = require("../config/cleaner-config.js");
  }
```

**Comment by emerleite** [comment]
Could you give me an example when it fails?

**Comment by knappe** [comment]
@emerleite Hopefully my commit explains the issue a bit better, but when installing node-database-cleaner via npm, it places the file in `node_modules/database-cleaner/lib/` and thus if we expect to use a custom config, we should try to read from the root dir and then default back to config provided by `node-database-cleaner`.

**Comment by emerleite** [comment]
@knappe thanks. I'll integrate today.

**Comment by knappe** [comment]
@emerleite Any chance you've been able to look into this?

**Comment by emerleite** [comment]
@knappe Done. Will release a new version.

**Comment by emerleite** [comment]
@knappe please use version 0.10.1 with your fix. Thanks for the contribution ;)
