### ISSUE TITLE
Disable trigger before delete and restart sequences

### ISSUE THREAD

**Issue by djibythiaw** [emerleite/node-database-cleaner#37]
Hi,

Thanks for that plugin. I'm using it in a postgres db project.

The problem I've is that when the plugin delete all tables, I've constraints errors because some table are linked to others so they can't be deleted. It's a good think to disable the triggers in the the table before doing the delete:

    db.query("ALTER TABLE " + "\"" + table['table_name'] + "\" DISABLE TRIGGER ALL", function() {
        ...
    }

And after delete we enable triggers

    db.query("ALTER TABLE " + "\"" + table['table_name'] + "\" ENABLE TRIGGER ALL", function() {
        ...
    }

The second think is also to restart the id sequences after delete. The plugin just delete datas but not restart the sequence.

    db.query("ALTER SEQUENCE IF EXISTS " + table['table_name'] + "_id_seq RESTART", function() {
        ...
    }

It won't be a good thing to have this features.

Thanks again

**Comment by emerleite** [comment]
Thanks @djibythiaw. How about send a pull request?

Cheers,

**Comment by djibythiaw** [comment]
Ok i will.
Le 13 janv. 2016 22:49, "Emerson Macedo" <notifications@github.com> a
écrit :

**Comment by emerleite** [comment]
@djibythiaw any news on this?

**Comment by djibythiaw** [comment]
Oupssss i forget it. Will do it soon. Sry
