### ISSUE TITLE
No reliable tests

### ISSUE THREAD

**Issue by kbariotis** [emerleite/node-database-cleaner#42]
Why are you doing such a [test](https://github.com/emerleite/node-database-cleaner/blob/master/test/mongodb.test.js#L60) when clearly you are dropping the [collections](https://github.com/emerleite/node-database-cleaner/blob/master/lib/database-cleaner.js#L18)?

**Comment by emerleite** [comment]
I guess it's wrong and should not delete system.indexes. I'll take a look on your fix PR.

**Comment by emerleite** [comment]
Closed by #43
