### ISSUE TITLE
Handle sequelize objects...and Promises

### ISSUE THREAD

**Issue by dynamiz77** [emerleite/node-database-cleaner#60]
Hello, thank you for this awesome library!

I'm trying to use this with sequelize (which relies on promises), could you please account for possibly a sequelize connection object and/or promises?
  Line 93 doesn't account for promises - just a callback:

https://github.com/emerleite/node-database-cleaner/blob/master/lib/database-cleaner.js#L93

Thank you!

**Comment by emerleite** [comment]
@dynamiz77 can you send a PR?
